
GET http://localhost:3000/songs/?page=1&limit=2


GET http://localhost:3001/songs/6




//access token
 "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlYmJ5a2xpbnRAZXhhbXBsZS5jb20iLCJzdWIiOjEwLCJpYXQiOjE3MzYwODQwMjcsImV4cCI6MTczNjE3MDQyN30.qruBHwNDhNkIO-iQJhvSu_w0AopcFvkDEp1KY8EKaHE"

GET http://localhost:3001/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlYmJ5a2xpbnRAZXhhbXBsZS5jb20iLCJzdWIiOjEwLCJpYXQiOjE3MzYyNDY0NjQsImV4cCI6MTczNjMzMjg2NH0.QublKCOk4mb5vOMLlb7uVadIxfr3WdQ8S7zdQPdax6g








GET http://localhost:3001/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InV5b3RpbW90aHlAZ21haWwuY29tIiwidXNlcklkIjoxMSwiYXJ0aXN0SWQiOjEwLCJpYXQiOjE3MzY0OTg3MTAsImV4cCI6MTczNjY3MTUxMH0.q7-z2NUzN4uN4yqN2LwZFu6eqbJP452qv3lHRN1QxA0

{
  "email": "uyotimothy@gmail.com",
  "password": "uyotim123"
}

GET http://localhost:3001/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InV5b3RpbW90aHlAZ21haWwuY29tIiwidXNlcklkIjoxMSwiYXJ0aXN0SWQiOjEwLCJpYXQiOjE3MzY0OTg3MTAsImV4cCI6MTczNjY3MTUxMH0.q7-z2NUzN4uN4yqN2LwZFu6eqbJP452qv3lHRN1QxA0

{
  "email": "uyotimothy@gmail.com",
  "password": "uyotim123"
}





//this request is for the api key for users that gets signed in 
GET http://localhost:3001/auth/profile
Authorization: Bearer d4081655-0d32-44a1-8743-fc58924b87e1
